/* globals Election */

class Controller { // eslint-disable-line no-unused-vars
	static setup () {
	  // https://www.electionresults.govt.nz/electionresults_2020_preliminary/
	  const theElection = new Election('NZ Election', 2023)
  // addParty Method now has 2 parameters - name and seats
	  theElection.addParty('ACT New Zealand', 1)
	  theElection.addParty('Advance NZ', 0)
	  theElection.addParty('Aotearoa Legalise Cannabis Party', 0)
	  theElection.addParty('Green Party', 1)
	  theElection.addParty('HeartlandNZ', 0)
	  theElection.addParty('Labour Party', 43)
	  theElection.addParty('Māori Party', 1)
	  theElection.addParty('National Party', 26)
	  theElection.addParty('New Conservative', 0)
	  theElection.addParty('New Zealand First Party', 0)
	  theElection.addParty('NZ Outdoors Party', 0)
	  theElection.addParty('ONE Party', 0)
	  theElection.addParty('Social Credit', 0)
	  theElection.addParty('Sustainable New Zealand Party', 0)
	  theElection.addParty('TEA Party', 0)
	  theElection.addParty('The Opportunities Party (TOP)', 0)
	  theElection.addParty('United Future', 0)
  
	  theElection.addElectorate('Auckland Central')
	  theElection.addElectorate('Banks Peninsula')
	  theElection.addElectorate('Bay of Plenty')
	  theElection.addElectorate('Botany')
	  theElection.addElectorate('Christchurch Central')
	  theElection.addElectorate('Christchurch East')
	  theElection.addElectorate('Coromandel')
	  theElection.addElectorate('Dunedin')
	  theElection.addElectorate('East Coast')
	  theElection.addElectorate('East Coast Bays')
	  theElection.addElectorate('Epsom')
	  theElection.addElectorate('Hamilton East')
	  theElection.addElectorate('Hamilton West')
	  theElection.addElectorate('Hutt South')
	  theElection.addElectorate('Ilam')
	  theElection.addElectorate('Invercargill')
	  theElection.addElectorate('Kaikōura')
	  theElection.addElectorate('Kaipara ki Mahurangi')
	  theElection.addElectorate('Kelston')
	  theElection.addElectorate('Mana')
	  theElection.addElectorate('Māngere')
	  theElection.addElectorate('Manurewa')
	  theElection.addElectorate('Maungakiekie')
	  theElection.addElectorate('Mt Albert')
	  theElection.addElectorate('Mt Roskill')
	  theElection.addElectorate('Napier')
	  theElection.addElectorate('Nelson')
	  theElection.addElectorate('New Lynn')
	  theElection.addElectorate('New Plymouth')
	  theElection.addElectorate('North Shore')
	  theElection.addElectorate('Northcote')
	  theElection.addElectorate('Northland')
	  theElection.addElectorate('Ōhāriu')
	  theElection.addElectorate('Ōtaki')
	  theElection.addElectorate('Pakuranga')
	  theElection.addElectorate('Palmerston')
	  theElection.addElectorate('Panmure-Ōtāhuhu')
	  theElection.addElectorate('Papakura')
	  theElection.addElectorate('Port Waikato')
	  theElection.addElectorate('Rangitata')
	  theElection.addElectorate('Rangitīkei')
	  theElection.addElectorate('Remutaka')
	  theElection.addElectorate('Rongotai')
	  theElection.addElectorate('Rotorua')
	  theElection.addElectorate('Selwyn')
	  theElection.addElectorate('Southland')
	  theElection.addElectorate('Taieri')
	  theElection.addElectorate('Takanini')
	  theElection.addElectorate('Tāmaki')
	  theElection.addElectorate('Taranaki-King Country')
	  theElection.addElectorate('Taupō')
	  theElection.addElectorate('Tauranga')
	  theElection.addElectorate('Te Atatū')
	  theElection.addElectorate('Tukituki')
	  theElection.addElectorate('Upper Harbour')
	  theElection.addElectorate('Waikato')
	  theElection.addElectorate('Waimakariri')
	  theElection.addElectorate('Wairarapa')
	  theElection.addElectorate('Waitaki')
	  theElection.addElectorate('Wellington Central')
	  theElection.addElectorate('West Coast-Tasman')
	  theElection.addElectorate('Whanganui')
	  theElection.addElectorate('Whangaparāoa')
	  theElection.addElectorate('Whangārei')
	  theElection.addElectorate('Wigram')
	  theElection.addElectorate('Hauraki-Waikato')
	  theElection.addElectorate('Ikaroa-Rāwhiti')
	  theElection.addElectorate('Tāmaki Makaurau')
	  theElection.addElectorate('Te Tai Hauāuru')
	  theElection.addElectorate('Te Tai Tokerau')
	  theElection.addElectorate('Te Tai Tonga')
	  theElection.addElectorate('Waiariki')
  
	  theElection.setWinningParty('Auckland Central', 'Green Party')
	  theElection.setWinningParty('Banks Peninsula', 'Labour Party')
	  theElection.setWinningParty('Bay of Plenty', 'National Party')
	  theElection.setWinningParty('Botany', 'National Party')
	  theElection.setWinningParty('Christchurch Central', 'Labour Party')
	  theElection.setWinningParty('Christchurch East', 'Labour Party')
	  theElection.setWinningParty('Coromandel', 'National Party')
	  theElection.setWinningParty('Dunedin', 'Labour Party')
	  theElection.setWinningParty('East Coast', 'Labour Party')
	  theElection.setWinningParty('East Coast Bays', 'National Party')
	  theElection.setWinningParty('Epsom', 'ACT New Zealand')
	  theElection.setWinningParty('Hamilton East', 'Labour Party')
	  theElection.setWinningParty('Hamilton West', 'Labour Party')
	  theElection.setWinningParty('Hutt South', 'Labour Party')
	  theElection.setWinningParty('Ilam', 'Labour Party')
	  theElection.setWinningParty('Invercargill', 'National Party')
	  theElection.setWinningParty('Kaikōura', 'National Party')
	  theElection.setWinningParty('Kaipara ki Mahurangi', 'National Party')
	  theElection.setWinningParty('Kelston', 'Labour Party')
	  theElection.setWinningParty('Mana', 'Labour Party')
	  theElection.setWinningParty('Māngere', 'Labour Party')
	  theElection.setWinningParty('Manurewa', 'Labour Party')
	  theElection.setWinningParty('Maungakiekie', 'National Party')
	  theElection.setWinningParty('Mt Albert', 'Labour Party')
	  theElection.setWinningParty('Mt Roskill', 'Labour Party')
	  theElection.setWinningParty('Napier', 'Labour Party')
	  theElection.setWinningParty('Nelson', 'Labour Party')
	  theElection.setWinningParty('New Lynn', 'Labour Party')
	  theElection.setWinningParty('New Plymouth', 'Labour Party')
	  theElection.setWinningParty('North Shore', 'National Party')
	  theElection.setWinningParty('Northcote', 'Labour Party')
	  theElection.setWinningParty('Northland', 'National Party')
	  theElection.setWinningParty('Ōhāriu', 'Labour Party')
	  theElection.setWinningParty('Ōtaki', 'Labour Party')
	  theElection.setWinningParty('Pakuranga', 'National Party')
	  theElection.setWinningParty('Palmerston', 'Labour Party')
	  theElection.setWinningParty('Panmure-Ōtāhuhu', 'Labour Party')
	  theElection.setWinningParty('Papakura', 'National Party')
	  theElection.setWinningParty('Port Waikato', 'National Party')
	  theElection.setWinningParty('Rangitata', 'Labour Party')
	  theElection.setWinningParty('Rangitīkei', 'National Party')
	  theElection.setWinningParty('Remutaka', 'Labour Party')
	  theElection.setWinningParty('Rongotai', 'Labour Party')
	  theElection.setWinningParty('Rotorua', 'National Party')
	  theElection.setWinningParty('Selwyn', 'National Party')
	  theElection.setWinningParty('Southland', 'National Party')
	  theElection.setWinningParty('Taieri', 'Labour Party')
	  theElection.setWinningParty('Takanini', 'Labour Party')
	  theElection.setWinningParty('Tāmaki', 'National Party')
	  theElection.setWinningParty('Taranaki-King Country', 'National Party')
	  theElection.setWinningParty('Taupō', 'National Party')
	  theElection.setWinningParty('Tauranga', 'National Party')
	  theElection.setWinningParty('Te Atatū', 'Labour Party')
	  theElection.setWinningParty('Tukituki', 'Labour Party')
	  theElection.setWinningParty('Upper Harbour', 'Labour Party')
	  theElection.setWinningParty('Waikato', 'National Party')
	  theElection.setWinningParty('Waimakariri', 'National Party')
	  theElection.setWinningParty('Wairarapa', 'Labour Party')
	  theElection.setWinningParty('Waitaki', 'National Party')
	  theElection.setWinningParty('Wellington Central', 'Labour Party')
	  theElection.setWinningParty('West Coast-Tasman', 'Labour Party')
	  theElection.setWinningParty('Whanganui', 'Labour Party')
	  theElection.setWinningParty('Whangaparāoa', 'National Party')
	  theElection.setWinningParty('Whangārei', 'National Party')
	  theElection.setWinningParty('Wigram', 'Labour Party')
	  theElection.setWinningParty('Hauraki-Waikato', 'Labour Party')
	  theElection.setWinningParty('Ikaroa-Rāwhiti', 'Labour Party')
	  theElection.setWinningParty('Tāmaki Makaurau', 'Labour Party')
	  theElection.setWinningParty('Te Tai Hauāuru', 'Labour Party')
	  theElection.setWinningParty('Te Tai Tokerau', 'Labour Party')
	  theElection.setWinningParty('Te Tai Tonga', 'Labour Party')
	  theElection.setWinningParty('Waiariki', 'Māori Party')
  
	  theElection.setVotePercent('ACT New Zealand', 8.0)
	  theElection.setVotePercent('Advance NZ', 0.9)
	  theElection.setVotePercent('Aotearoa Legalise Cannabis Party', 0.3)
	  theElection.setVotePercent('Green Party', 7.6)
	  theElection.setVotePercent('HeartlandNZ', 0.0)
	  theElection.setVotePercent('Labour Party', 49.1)
	  theElection.setVotePercent('Māori Party', 1.0)
	  theElection.setVotePercent('National Party', 26.8)
	  theElection.setVotePercent('New Conservative', 1.5)
	  theElection.setVotePercent('New Zealand First Party', 2.7)
	  theElection.setVotePercent('NZ Outdoors Party', 0.1)
	  theElection.setVotePercent('ONE Party', 0.3)
	  theElection.setVotePercent('Social Credit', 0.1)
	  theElection.setVotePercent('Sustainable New Zealand Party', 0.1)
	  theElection.setVotePercent('TEA Party', 0.1)
	  theElection.setVotePercent('The Opportunities Party (TOP)', 1.4)
	  theElection.setVotePercent('United Future', 0.1)
  // findElectorate -> Christchurch Central
	  const theElectorate = theElection.findElectorate('Christchurch Central')
  // addCandidate in the Electorate 
	  theElectorate.addCandidate('GASKIN, Ian Camden', 'United Future')
	  theElectorate.addCandidate('HILL, Douglas MacMillan', 'The Opportunities Party (TOP)')
	  theElectorate.addCandidate('RICHARDSON, Peter Ian', 'Green Party')
	  theElectorate.addCandidate('ROBINSON, Philip John', 'New Zealand First Party')
	  theElectorate.addCandidate('HERBERT-SHUFFLEBOTHAM, Janine Anne', 'Aotearoa Legalise Cannabis Party')
	  theElectorate.addCandidate('WAGNER, Nicola Joanne', 'National Party')
	  theElectorate.addCandidate('WEBB, Duncan Alexander', 'Labour Party')
  // setCandidateVote()
	  theElectorate.setCandidateVote('GASKIN, Ian Camden', 80)
	  theElectorate.setCandidateVote('HILL, Douglas MacMillan', 879)
	  theElectorate.setCandidateVote('RICHARDSON, Peter Ian', 1957)
	  theElectorate.setCandidateVote('ROBINSON, Philip John', 1091)
	  theElectorate.setCandidateVote('HERBERT-SHUFFLEBOTHAM, Janine Anne', 304)
	  theElectorate.setCandidateVote('WAGNER, Nicola Joanne', 13760)
	  theElectorate.setCandidateVote('WEBB, Duncan Alexander', 16631)
  
	  return theElection
	}
}


// class Controller  {
// 	static setup () {
		
// 		let theElection

// 		theElection = new Election('New Zealand Election',2023)
// 		theElection.addParty('ACT New Zealand')
// 		theElection.addParty('Aotearoa Legalise Cannabis Party')
// 		theElection.addParty('Heartland New Zealand Party')
// 		theElection.addParty('MANA Movement')
// 		theElection.addParty('Māori Party')
// 		theElection.addParty('New Conservative')
// 		theElection.addParty('New Zealand First Party')
// 		theElection.addParty('New Zealand Labour Party')
// 		theElection.addParty('New Zealand TEA Party')
// 		theElection.addParty('NZ Outdoors Party')
// 		theElection.addParty('ONE Party')
// 		theElection.addParty('Sustainable New Zealand Party')
// 		theElection.addParty('The Advance New Zealand Party')
// 		theElection.addParty('The Green Party of Aotearoa/New Zealand')
// 		theElection.addParty('The New Zealand Democratic Party for Social Credit')
// 		theElection.addParty('The New Zealand National Party')
// 		theElection.addParty('The Opportunities Party (TOP)')
// 		theElection.addParty('Vision New Zealand')

// 		theElection.addElectorate('Auckland Central', 'The New Zealand National Party')
// 		theElection.addElectorate('Bay of Plenty', 'The New Zealand National Party')
// 		theElection.addElectorate('Botany', 'The Advance New Zealand Party')
// 		theElection.addElectorate('Christchurch Central', 'New Zealand Labour Party')
// 		theElection.addElectorate('Christchurch East', 'New Zealand Labour Party')
// 		theElection.addElectorate('Clutha-Southland', 'The New Zealand National Party')
// 		theElection.addElectorate('Coromandel', 'The New Zealand National Party')
// 		theElection.addElectorate('Dunedin North', 'New Zealand Labour Party')
// 		theElection.addElectorate('Dunedin South', 'New Zealand Labour Party')
// 		theElection.addElectorate('East Coast', 'The New Zealand National Party')
// 		theElection.addElectorate('East Coast Bays', 'The New Zealand National Party')
// 		theElection.addElectorate('Epsom', 'ACT New Zealand')
// 		theElection.addElectorate('Hamilton East', 'The New Zealand National Party')
// 		theElection.addElectorate('Hamilton West', 'The New Zealand National Party')
// 		theElection.addElectorate('Helensville', 'The New Zealand National Party')
// 		theElection.addElectorate('Hunua', 'The New Zealand National Party')
// 		theElection.addElectorate('Hutt South', 'The New Zealand National Party')
// 		theElection.addElectorate('Ilam', 'The New Zealand National Party')
// 		theElection.addElectorate('Invercargill', 'The New Zealand National Party')
// 		theElection.addElectorate('Kaikōura', 'The New Zealand National Party')
// 		theElection.addElectorate('Kelston', 'New Zealand Labour Party')
// 		theElection.addElectorate('Mana', 'New Zealand Labour Party')
// 		theElection.addElectorate('Māngere', 'New Zealand Labour Party')
// 		theElection.addElectorate('Manukau East', 'New Zealand Labour Party')
// 		theElection.addElectorate('Manurewa', 'New Zealand Labour Party')
// 		theElection.addElectorate('Maungakiekie', 'The New Zealand National Party')
// 		theElection.addElectorate('Mt Albert', 'New Zealand Labour Party')
// 		theElection.addElectorate('Mt Roskill', 'New Zealand Labour Party')
// 		theElection.addElectorate('Napier', 'New Zealand Labour Party')
// 		theElection.addElectorate('Nelson', 'The New Zealand National Party')
// 		theElection.addElectorate('New Lynn', 'New Zealand Labour Party')
// 		theElection.addElectorate('New Plymouth', 'The New Zealand National Party')
// 		theElection.addElectorate('North Shore', 'The New Zealand National Party')
// 		theElection.addElectorate('Northcote', 'The New Zealand National Party')
// 		theElection.addElectorate('Northland', 'The New Zealand National Party')
// 		theElection.addElectorate('Ōhariu', 'New Zealand Labour Party')
// 		theElection.addElectorate('Ōtaki', 'The New Zealand National Party')
// 		theElection.addElectorate('Pakuranga', 'The New Zealand National Party')
// 		theElection.addElectorate('Palmerston North', 'New Zealand Labour Party')
// 		theElection.addElectorate('Port Hills', 'New Zealand Labour Party')
// 		theElection.addElectorate('Papakura', 'The New Zealand National Party')
// 		theElection.addElectorate('Rangitata', 'The New Zealand National Party')
// 		theElection.addElectorate('Rangitīkei', 'The New Zealand National Party')
// 		theElection.addElectorate('Rimutaka', 'New Zealand Labour Party')
// 		theElection.addElectorate('Rodney', 'The New Zealand National Party')
// 		theElection.addElectorate('Rongotai', 'New Zealand Labour Party')
// 		theElection.addElectorate('Rotorua', 'The New Zealand National Party')
// 		theElection.addElectorate('Selwyn', 'The New Zealand National Party')
// 		theElection.addElectorate('Tāmaki', 'The New Zealand National Party')
// 		theElection.addElectorate('Taranaki-King Country', 'The New Zealand National Party')
// 		theElection.addElectorate('Taupō', 'The New Zealand National Party')
// 		theElection.addElectorate('Tauranga', 'The New Zealand National Party')
// 		theElection.addElectorate('Te Atatū', 'New Zealand Labour Party')
// 		theElection.addElectorate('Tukituki', 'The New Zealand National Party')
// 		theElection.addElectorate('Upper Harbour', 'The New Zealand National Party')
// 		theElection.addElectorate('Waikato', 'The New Zealand National Party')
// 		theElection.addElectorate('Waimakariri', 'The New Zealand National Party')
// 		theElection.addElectorate('Wairarapa', 'The New Zealand National Party')
// 		theElection.addElectorate('Waitaki', 'The New Zealand National Party')
// 		theElection.addElectorate('Wellington Central', 'New Zealand Labour Party')
// 		theElection.addElectorate('West Coast-Tasman', 'New Zealand Labour Party')
// 		theElection.addElectorate('Whanganui', 'The New Zealand National Party')
// 		theElection.addElectorate('Whangarei', 'The New Zealand National Party')
// 		theElection.addElectorate('Wigram', 'New Zealand Labour Party')
// 		theElection.addElectorate('Hauraki-Waikato', 'New Zealand Labour Party')
// 		theElection.addElectorate('Ikaroa-Rāwhiti', 'New Zealand Labour Party')
// 		theElection.addElectorate('Tāmaki Makaurau', 'New Zealand Labour Party')
// 		theElection.addElectorate('Te Tai Hauāuru', 'New Zealand Labour Party')
// 		theElection.addElectorate('Te Tai Tokerau', 'New Zealand Labour Party')
// 		theElection.addElectorate('Te Tai Tonga', 'New Zealand Labour Party')
// 		return theElection
// 	}
// }