class Controller  {
	static setup () {
		
		let theElection

		theElection = new Election('New Zealand Election',2023)
		theElection.addParty('ACT New Zealand')
		theElection.addParty('Aotearoa Legalise Cannabis Party')
		theElection.addParty('Heartland New Zealand Party')
		theElection.addParty('MANA Movement')
		theElection.addParty('Māori Party')
		theElection.addParty('New Conservative')
		theElection.addParty('New Zealand First Party')
		theElection.addParty('New Zealand Labour Party')
		theElection.addParty('New Zealand TEA Party')
		theElection.addParty('NZ Outdoors Party')
		theElection.addParty('ONE Party')
		theElection.addParty('Sustainable New Zealand Party')
		theElection.addParty('The Advance New Zealand Party')
		theElection.addParty('The Green Party of Aotearoa/New Zealand')
		theElection.addParty('The New Zealand Democratic Party for Social Credit')
		theElection.addParty('The New Zealand National Party')
		theElection.addParty('The Opportunities Party (TOP)')
		theElection.addParty('Vision New Zealand')

		theElection.addElectorate('Auckland Central', 'The New Zealand National Party')
		theElection.addElectorate('Bay of Plenty', 'The New Zealand National Party')
		theElection.addElectorate('Botany', 'The Advance New Zealand Party')
		theElection.addElectorate('Christchurch Central', 'New Zealand Labour Party')
		theElection.addElectorate('Christchurch East', 'New Zealand Labour Party')
		theElection.addElectorate('Clutha-Southland', 'The New Zealand National Party')
		theElection.addElectorate('Coromandel', 'The New Zealand National Party')
		theElection.addElectorate('Dunedin North', 'New Zealand Labour Party')
		theElection.addElectorate('Dunedin South', 'New Zealand Labour Party')
		theElection.addElectorate('East Coast', 'The New Zealand National Party')
		theElection.addElectorate('East Coast Bays', 'The New Zealand National Party')
		theElection.addElectorate('Epsom', 'ACT New Zealand')
		theElection.addElectorate('Hamilton East', 'The New Zealand National Party')
		theElection.addElectorate('Hamilton West', 'The New Zealand National Party')
		theElection.addElectorate('Helensville', 'The New Zealand National Party')
		theElection.addElectorate('Hunua', 'The New Zealand National Party')
		theElection.addElectorate('Hutt South', 'The New Zealand National Party')
		theElection.addElectorate('Ilam', 'The New Zealand National Party')
		theElection.addElectorate('Invercargill', 'The New Zealand National Party')
		theElection.addElectorate('Kaikōura', 'The New Zealand National Party')
		theElection.addElectorate('Kelston', 'New Zealand Labour Party')
		theElection.addElectorate('Mana', 'New Zealand Labour Party')
		theElection.addElectorate('Māngere', 'New Zealand Labour Party')
		theElection.addElectorate('Manukau East', 'New Zealand Labour Party')
		theElection.addElectorate('Manurewa', 'New Zealand Labour Party')
		theElection.addElectorate('Maungakiekie', 'The New Zealand National Party')
		theElection.addElectorate('Mt Albert', 'New Zealand Labour Party')
		theElection.addElectorate('Mt Roskill', 'New Zealand Labour Party')
		theElection.addElectorate('Napier', 'New Zealand Labour Party')
		theElection.addElectorate('Nelson', 'The New Zealand National Party')
		theElection.addElectorate('New Lynn', 'New Zealand Labour Party')
		theElection.addElectorate('New Plymouth', 'The New Zealand National Party')
		theElection.addElectorate('North Shore', 'The New Zealand National Party')
		theElection.addElectorate('Northcote', 'The New Zealand National Party')
		theElection.addElectorate('Northland', 'The New Zealand National Party')
		theElection.addElectorate('Ōhariu', 'New Zealand Labour Party')
		theElection.addElectorate('Ōtaki', 'The New Zealand National Party')
		theElection.addElectorate('Pakuranga', 'The New Zealand National Party')
		theElection.addElectorate('Palmerston North', 'New Zealand Labour Party')
		theElection.addElectorate('Port Hills', 'New Zealand Labour Party')
		theElection.addElectorate('Papakura', 'The New Zealand National Party')
		theElection.addElectorate('Rangitata', 'The New Zealand National Party')
		theElection.addElectorate('Rangitīkei', 'The New Zealand National Party')
		theElection.addElectorate('Rimutaka', 'New Zealand Labour Party')
		theElection.addElectorate('Rodney', 'The New Zealand National Party')
		theElection.addElectorate('Rongotai', 'New Zealand Labour Party')
		theElection.addElectorate('Rotorua', 'The New Zealand National Party')
		theElection.addElectorate('Selwyn', 'The New Zealand National Party')
		theElection.addElectorate('Tāmaki', 'The New Zealand National Party')
		theElection.addElectorate('Taranaki-King Country', 'The New Zealand National Party')
		theElection.addElectorate('Taupō', 'The New Zealand National Party')
		theElection.addElectorate('Tauranga', 'The New Zealand National Party')
		theElection.addElectorate('Te Atatū', 'New Zealand Labour Party')
		theElection.addElectorate('Tukituki', 'The New Zealand National Party')
		theElection.addElectorate('Upper Harbour', 'The New Zealand National Party')
		theElection.addElectorate('Waikato', 'The New Zealand National Party')
		theElection.addElectorate('Waimakariri', 'The New Zealand National Party')
		theElection.addElectorate('Wairarapa', 'The New Zealand National Party')
		theElection.addElectorate('Waitaki', 'The New Zealand National Party')
		theElection.addElectorate('Wellington Central', 'New Zealand Labour Party')
		theElection.addElectorate('West Coast-Tasman', 'New Zealand Labour Party')
		theElection.addElectorate('Whanganui', 'The New Zealand National Party')
		theElection.addElectorate('Whangarei', 'The New Zealand National Party')
		theElection.addElectorate('Wigram', 'New Zealand Labour Party')
		theElection.addElectorate('Hauraki-Waikato', 'New Zealand Labour Party')
		theElection.addElectorate('Ikaroa-Rāwhiti', 'New Zealand Labour Party')
		theElection.addElectorate('Tāmaki Makaurau', 'New Zealand Labour Party')
		theElection.addElectorate('Te Tai Hauāuru', 'New Zealand Labour Party')
		theElection.addElectorate('Te Tai Tokerau', 'New Zealand Labour Party')
		theElection.addElectorate('Te Tai Tonga', 'New Zealand Labour Party')
		return theElection
	}
}